version: "3.8"

services:
  backoffice:
    build:
      context: .
      dockerfile: apps/backoffice/Dockerfile
    container_name: finance-app-backoffice
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_UPLOADER_ROOT_URL=http://finance-app-uploader-root:4200
      - NEXT_PUBLIC_UPLOADER_ANGULAR_URL=http://finance-app-uploader-angular:4201
      - NEXT_PUBLIC_BACKOFFICE_URL=http://localhost:3000
      - NEXT_PUBLIC_DASHBOARD_URL=http://finance-app-dashboard:3001
    networks:
      - finance-app-network
    depends_on:
      - uploader-root
      - uploader-angular
      - dashboard

  uploader-root:
    build:
      context: .
      dockerfile: apps/uploader/root/Dockerfile
    container_name: finance-app-uploader-root
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    networks:
      - finance-app-network
    depends_on:
      - uploader-angular

  dashboard:
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile
    container_name: finance-app-dashboard
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - finance-app-network

  uploader-angular:
    build:
      context: .
      dockerfile: apps/uploader/app-angular/Dockerfile
    container_name: finance-app-uploader-angular
    ports:
      - "4201:4201"
    environment:
      - NODE_ENV=development
    networks:
      - finance-app-network

  storybook:
    build:
      context: .
      dockerfile: apps/backoffice/Dockerfile.storybook
    container_name: finance-app-storybook
    ports:
      - "6006:6006"
    environment:
      - NODE_ENV=development
    networks:
      - finance-app-network
    depends_on:
      - backoffice

networks:
  finance-app-network:
    driver: bridge
